// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcrdwjukkchdibmpyjkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjcmR3anVra2NoZGlibXB5amtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MDk3MDMsImV4cCI6MjA4NDE4NTcwM30.ftY9rk9WDNSF_GNMgFocTXL8kBfZpeJMVHvh7x9jHEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});